### ISSUE TITLE
npm run build报错,因为有个github资源404

### ISSUE THREAD

**Issue by Suntz246** [onlyGuo/dnf-client-public#1]
之前我也遇到过类似的404，可能和npm版本有关，当时项目使用的npm版本是多少？

> OKAY  take it away `electron-builder`
  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build\builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=2.0.18 appOutDir=build\win-unpacked
  • building        target=nsis file=build\dnf-client-32 Setup 0.0.1.exe archs=x64 oneClick=true perMachine=false
  ⨯ Get https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.3.0/nsis-resources-3.3.0.7z: read tcp 192.168.124.4:8948->140.82.112.3:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:171
github.com/develar/app-builder/pkg/download.(*Downloader).follow
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:204
github.com/develar/app-builder/pkg/download.(*Downloader).Download
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:79
github.com/develar/app-builder/pkg/download.DownloadArtifact
        /Volumes/data/Documents/app-builder/pkg/download/artifactDownloader.go:109
github.com/develar/app-builder/pkg/download.ConfigureArtifactCommand.func1
        /Volumes/data/Documents/app-builder/pkg/download/artifactDownloader.go:26
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:78
runtime.main
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/proc.go:200
runtime.goexit
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:1337
>Error: F:\DNF\dnf-client-public-main\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.<anonymous> (F:\DNF\dnf-client-public-main\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
From previous event:
    at AsyncTaskManager.add (F:\DNF\dnf-client-public-main\node_modules\builder-util\src\asyncTaskManager.ts:14:20)
    at F:\DNF\dnf-client-public-main\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:534:17
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.computeCommonInstallerScriptHeader (F:\DNF\dnf-client-public-main\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:517:51)
    at F:\DNF\dnf-client-public-main\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:263:37
From previous event:
    at NsisTarget.buildInstaller (F:\DNF\dnf-client-public-main\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:125:31)
    at F:\DNF\dnf-client-public-main\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:109:18
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.finishBuild (F:\DNF\dnf-client-public-main\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:107:20)
    at F:\DNF\dnf-client-public-main\node_modules\app-builder-lib\src\packager.ts:438:36
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Packager.doBuild (F:\DNF\dnf-client-public-main\node_modules\app-builder-lib\src\packager.ts:396:24)
    at F:\DNF\dnf-client-public-main\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at F:\DNF\dnf-client-public-main\node_modules\graceful-fs\graceful-fs.js:143:16
    at F:\DNF\dnf-client-public-main\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:171:23)
From previous event:
    at Packager._build (F:\DNF\dnf-client-public-main\node_modules\app-builder-lib\src\packager.ts:335:133)
    at F:\DNF\dnf-client-public-main\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Packager.build (F:\DNF\dnf-client-public-main\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (F:\DNF\dnf-client-public-main\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (F:\DNF\dnf-client-public-main\node_modules\electron-builder\src\builder.ts:228:10)
    at F:\DNF\dnf-client-public-main\node_modules\electron-builder\src\cli\cli.ts:49:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dnf-client-32@0.0.1 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dnf-client-32@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by onlyGuo** [comment]
在终端添加科学工具，清除.lok文件和node_modules文件夹，并重新执行yarn
